### ISSUE TITLE
Add/indicate Minecraft 1.20.5/6 support

### ISSUE THREAD

**Issue by BrailleBennett** [rockquiet/Spawn#10]
This plugin looks like exactly what I need. I'm assuming it doesn't work on 1.20.6 though, as most plugins broke. Could you please add support for it? Thank you for all your work on this.

**Comment by rockquiet** [comment]
Hi, I'm glad you're interested in the plugin! 1.20.5/6 is fully working as I tested, no changes needed :)

I usually update the list of supported versions (of the latest release) on Modrinth (https://modrinth.com/plugin/spawn/versions).
But to make it more clear, I will probably add it in more places.

If you encounter any problems, please feel free to report them.
